Implemented CLI into Mission_blue.py  | Removed CLI.py
Team-Mission-Blue/MissionBlueAPI pull request #20
Opened 2024-12-24 02:27 UTC by andewmark

Users can now call our missionBlue script using flags based on their inputted params

2024-12-24 04:55 UTC, Lementknight commented
Nice work so far! I look forward to view pr once it is ready.

2024-12-24 21:03 UTC, Lementknight requested changes

2024-12-24 21:03 UTC, Lementknight commented on README.md
Please update the README to explain how to use the cli.

2024-12-26 05:33 UTC, andewmark commented on README.md
will do! Will be completed by EOD tomorrow

2025-01-02 20:27 UTC, Lementknight approved these changes
LGTM

2025-01-02 20:28 UTC, Lementknight approved these changes
LGTM

2025-01-02 20:28 UTC, Lementknight approved these changes
LGTM

2025-01-02 20:29 UTC, merged